namespace OpenLMStudio.Application.Types;

/// <summary>
/// Represents a message in a chat conversation.
/// </summary>
public class ChatMessage
{
    /// <summary>
    /// The role of the message sender (system, user, assistant).
    /// </summary>
    public string Role { get; set; } = string.Empty;

    /// <summary>
    /// The content text of the message.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Optional name/identifier for tool calls within this message.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Tool call ID if this message contains a tool result.
    /// </summary>
    public string? ToolCallId { get; set; }
}

/// <summary>
/// Request to the chat completion service for generating a response.
/// </summary>
public class ChatCompletionRequest
{
    /// <summary>
    /// The model identifier to use for completion.
    /// </summary>
    public string ModelId { get; set; } = string.Empty;

    /// <summary>
    /// Array of messages forming the conversation context.
    /// </summary>
    public List<ChatMessage> Messages { get; set; } = new();

    /// <summary>
    /// Sampling temperature (0.0 - 2.0). Higher values produce more creative outputs.
    /// </summary>
    public float Temperature { get; set; } = 0.7f;

    /// <summary>
    /// Top-p sampling parameter for nucleus sampling.
    /// </summary>
    public float? TopP { get; set; }

    /// <summary>
    /// Maximum number of tokens to generate in the response.
    /// </summary>
    public int MaxTokens { get; set; } = 4096;

    /// <summary>
    /// Whether to stream the response token by token.
    /// </summary>
    public bool Stream { get; set; }

    /// <summary>
    /// Stop sequences that will terminate generation early.
    /// </summary>
    public List<string>? StopSequences { get; set; }

    /// <summary>
    /// Number of values to consider for each token (n-gram sampling).
    /// </summary>
    public int N { get; set; } = 1;

    /// <summary>
    /// Model type for multi-engine routing. Defaults to null (text generation).
    /// Accepts: "image" for image generation, "embedding" for embedding models.
    /// </summary>
    public string? Type { get; set; }
}

/// <summary>
/// Represents a single choice within a chat completion response.
/// </summary>
public class ChatChoice
{
    /// <summary>
    /// The index of this choice among all choices returned.
    /// </summary>
    public int Index { get; set; }

    /// <summary>
    /// The message content generated by the model.
    /// </summary>
    public ChatMessage? Message { get; set; }

    /// <summary>
    /// The finish reason indicating why generation stopped (e.g., "stop", "length").
    /// </summary>
    public string? FinishReason { get; set; }

    /// <summary>
    /// Number of tokens used for this choice.
    /// </summary>
    public int? CompletionTokens { get; set; }

    /// <summary>
    /// Token usage statistics for the entire request (includes prompt tokens).
    /// </summary>
    public UsageStats? Usage { get; set; }
}

/// <summary>
/// Response from a chat completion request.
/// </summary>
public class ChatCompletionResponse
{
    /// <summary>
    /// List of possible choices returned by the model.
    /// </summary>
    public List<ChatChoice> Choices { get; set; } = new();

    /// <summary>
    /// The model identifier used for this completion.
    /// </summary>
    public string ModelId { get; set; } = string.Empty;

    /// <summary>
    /// Token usage statistics for the entire request.
    /// </summary>
    public UsageStats? Usage { get; set; }

    /// <summary>
    /// Timestamp when the response was generated.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Token usage statistics for a completion request.
/// </summary>
public class UsageStats
{
    /// <summary>
    /// Number of tokens in the prompt/context.
    /// </summary>
    public int PromptTokens { get; set; }

    /// <summary>
    /// Number of tokens generated in the completion.
    /// </summary>
    public int CompletionTokens { get; set; }

    /// <summary>
    /// Total number of tokens used (prompt + completion).
    /// </summary>
    public int TotalTokens => PromptTokens + CompletionTokens;
}

/// <summary>
/// Event arguments for streaming token delivery.
/// </summary>
public class StreamingEventArgs : EventArgs
{
    /// <summary>
    /// The token text fragment received in this chunk.
    /// </summary>
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// Whether this is the final chunk of the stream.
    /// </summary>
    public bool IsDone { get; set; }

    /// <summary>
    /// Usage statistics when streaming completes (only available on final chunk).
    /// </summary>
    public UsageStats? FinalUsage { get; set; }
}

/// <summary>
/// Handler delegate for streaming token events.
/// </summary>
public delegate void StreamingEventHandler(object? sender, StreamingEventArgs e);

/// <summary>
/// Anthropic request DTO that supports model type routing via the optional "type" parameter.
/// Used by /v1/messages endpoint to route requests across different inference engines.
/// </summary>
internal record ContentBlock(
    string Type = "text",
    string? Text = null);

internal record AnthropicMessage(
    string Role = "user",
    List<ContentBlock>? ContentBlocks = null)
{
    /// <summary>Convenience accessor: returns the text content from all 'text' type content blocks.</summary>
    public string? Content => ContentBlocks != null && ContentBlocks.Any(cb => cb.Type == "text")
        ? string.Join("\n", ContentBlocks.Where(cb => cb.Type == "text").Select(cb => cb.Text!).Where(s => s != null)!)
        : null;
}

internal record AnthropicRequestWithModelType(
    string? Model = null,
    double? Temperature = 0.7,
    int MaxTokens = 4096,
    float? TopP = 1.0f,
    List<AnthropicMessage>? Messages = null,
    string? System = null,
    /// <summary>Model type for multi-engine routing: text (default), image, embedding.</summary>
    string? ModelType = null);
