// Assembly info for Avalonia app — no need for WPF-style ThemeInfo attributes since styles are defined in App.axaml
using System.Reflection;

// The .NET SDK auto-generates Company, Product, Title, and Version attributes from the csproj XML elements.
// We only add copyright here since it's not generated by default.
[assembly: AssemblyCopyright("© 2026 OpenLMStudio Contributors. All rights reserved.")]
